accounts/urls.py
from django.conf.urls import url
from .views import (
    RegistrationView, LoginView, LogoutView
)
urlpatterns = [
    url(r'^registration/$', RegistrationView.as_view(), name="registration"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
]

ldream/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ldream.views import IndexView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'), name='accounts'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic import RedirectView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.auth import logout as auth_logout
# Create your views here.

class RegistrationView(SuccessMessageMixin, CreateView):

    model = User
    form_class = UserCreationForm
    template_name = 'accounts/registration/registration.html'
    success_url = reverse_lazy('index')
    success_message = "Welcome %(user)s to our website"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict( cleaned_data, user=self.object.username)

class LoginView(SuccessMessageMixin, LoginView):

    template_name = 'accounts/registration/login.html'
    success_message = "%(user)s login successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict( cleaned_data, user=self.request.user)

class LogoutView(RedirectView):
	url = reverse_lazy('accounts:login')
	def get(self, request, *args, **kwargs):
		auth_logout(request)
		messages.add_message(request, messages.INFO, 'Logged out.')
		return super(LogoutView, self).get(request, *args, **kwargs)
"""class LogoutView(SuccessMessageMixin, LogoutView):

    template_name = 'accounts/registration/logout.html'
    success_message = "%(user)s login successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, user=self.request.user)"""

ldream/views.py
from django.views.generic import TemplateView
class IndexView(TemplateView):
    template_name = "base/base.html"

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
    {% load static %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">

    <!-- jQuery library -->
    <script src="{% static 'libs/jquery-3.2.1.min.js' %}"></script>

    <!-- Latest compiled JavaScript -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
     <!-- Static navbar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">ldream</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Sign In</a></li>
                        <li><a href="{% url 'accounts:registration' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

    {% if messages %}
	    {% for message in messages %}
		    <div class="panel panel-success">
			    <div class="panel-body">{{message}}</div>
		    </div>
	    {% endfor %}
    {% endif %}
</div>
    {% block content %}
    {% endblock %}
</body>
</html>